const questions = [
  "Všetci chlapci si vypijú... a dajú kompliment osobe po svojej pravici",
  "Čoho sa bojíš viac než pondelka ráno?",
  "Povedz najlepší (alebo najhlúpejší) vtip, aký poznáš",
  "Čo ťa vytočí tak, že by si najradšej hodil/a ovládač o stenu?",
  "3. osoba naľavo od teba – pohárik a story z detstva!",
  "Všetky ženy si dajú panáka... alebo povedia svoju guilty pleasure",
  "Vypi, alebo označ hráča, ktorý vypije za teba... a povie tvoju najlepšiu vlastnosť",
  "Vyber si osobu, s ktorou by si prežil zombie apokalypsu – a prečo práve ona?",
  "Čo by si na sebe zmenil/a... okrem exa?",
  "S kým z hráčov by si si vedel/a predstaviť prespať na gauči... nahý/á?",
  "Vymysli nový produkt... ktorý by vyriešil problém: opitosť bez hanby",
  "Povedz, prečo by si šiel/šla na rande s hráčom podľa vlastného výberu... aj keby mal/a Crocsy",
  "Ktorý hráč je podľa teba Batman... a kto určite Robin? Zdôvodni!",
  "So ktorou celebritou by si najradšej mal/a horúcu letnú aféru?",
  "Ak ti padlo nepárne číslo – piješ. Ak párne – piješ s osobou po pravici.",
  "Tvoj najbizarnejší zlozvyk, ktorý ťa (ne)robí sexy?",
  "Vyber hráča a povedz, čo ťa na ňom vytáča... s láskou ❤️",
  "Názov tvojej biografie... ktorá sa stane Netflix hitom",
  "Kde budeš o 10 rokov... a koho z prítomných budeš mať stále v živote?",
  "Tvoja najväčšia slabosť... ktorú považuješ za sexy",
];

const challengeTasks = [
  "Vymenuj všetkých 6 šachových figúrok – bez Googlu!",
  "Vyzuj si obidve ponožky a daj si ich na ruky na 2 kolá",
  "Vymenuj 4 mestá v ČR... ktoré nie sú Praha (easy mode off)",
  "Vymenuj 4 hlavné mestá mimo Európy... a pridaj k nim drink, ktorý tam určite pijú",
  "Prines niečo kovové a povedz, prečo je to sexy",
  "Vymenuj 5 mien na P... a povedz, s ktorým by si sa vyspal/a",
  'Postni fotku na story s textom: "Ten večer začína nevinne..."',
  "Prines niečo žlté a povedz, aké by to bolo, keby to bolo živé",
  "Prines niečo drevené a povedz, na čo by sa to dalo použiť v 50 odtieňoch sivej",
  "Zlož 4-veršovú báseň o alkohole a hanbe",
  "Vypi. Ale najprv povedz „na čo“ piješ dnes najviac",
  "Sprav 5 drepov... pri každom povedz jednu nadávku (neopakovateľnú!)",
  "Urob selfie a pošli ju osobe, s ktorou si mal/a najhoršie rande",
];

const duel = [
  "Strihnite si – kto prehrá, vypije 2x",
  "Kto skôr žmurkne – prehrávajúci rozpráva s prízvukom ďalšie 2 kolá",
  "Kto sa skôr zasmeje – prehráva a musí povedať trápnu historku",
  "Palcová hra – kto prehrá, urobí kompliment tomu druhému v rýmoch",
  "Pretláčanie rukou – alebo pohľadom, ak chcete menej fyzicky",
  "Otvor SMS aplikáciu so zavretými očami a prečítaj 1. slovo, ktoré uvidíš – vymysli z neho vtip",
];

const tasks = [
  "Vypi – alebo sa snaž 10 sekúnd flirtovať s fľašou",
  "Vyzleč si 1 vec... bez toho, aby si povedal/a čo to je",
  "Vymieňaj si s hráčom veci, kým sa necítite trápne",
  "Prehovor kanibala, aby ťa nezjedol... ako keby si bol/a nahý/á a smrdíš",
  "Vezmi predmet a drž ho oboma rukami celé 2 kolá – aj ak budeš piť!",
  "Zahraj sa na plačúce dieťa, ktoré nedostalo iPhone",
  "Zahryzni si do jazyka a odrecituj abecedu – a názov porno stránky",
  "Skús si olízať lakeť... a popíš to zmyselne",
  "Vydrž lastovičku aspoň 5 sekúnd – alebo vypi!",
  "Nechaj sa šteklit 7 sekúnd – alebo zaspievaj Despacito",
  "Rozosmej hráča do 10 sekúnd – ak nie, piješ ty",
  "Nakresli trojuholník jednou rukou, kruh druhou – a oboje súčasne nazvi „umenie“",
  "Osoba po ľavici ti dá symbolickú facku... alebo pusu",
  "Vymenuj 5 zvierat, ktoré by v ZOO určite robili bordel",
  "Vymenuj 3 veci, ktoré pokazili tvoje rande... a ktoré by ho vylepšili",
];

const facts = [
  "Tvoja najtrápnejšia story – nech to bolí!",
  "Kedy si sa prvýkrát opil – a kde si sa zobudil/a?",
  "Skúsil/a si marihuanu? Opíš to ako review na Google",
  "Kedy si sa najviac strápnil/a pred crushom?",
  "Vyber hráča a povedz o ňom niečo... čo by možno nechcel vedieť jeho ex",
  "Už si čúral/a v bazéne? Sám/a? Svedkovia?",
  "Koľko ľudí si bozkával/a za posledný rok?",
  "Popíš posledný priestupok... a daj mu hodnotenie zábavnosti (1–10)",
  "Kedy si sa najviac opil/a a čo ťa prebudilo?",
  "Akú najtrápnejšiu vec si si kúpil/a – a ešte ju máš?",
  "Najbizárnejšie miesto, kde si zaspal/a – a prečo si tam bol/a?",
  "Ukradol/a si niečo? A ak áno, bolo to aspoň worth it?",
  "Ako dlho si sa najviac nesprchoval/a... a prečo?",
];

const questions18Plus = [
  "Aký najdivokejší sexuálny zážitok si mal/a?",
  "Na aké miesto na tele ťa najviac vzrušuje dotyk?",
  "Máš sexi fantáziu, o ktorej si ešte nikomu nepovedal/a?",
  "Používaš hračky v spálni? Ak áno – ktoré odporúčaš?",
  "S ktorým hráčom/by si si najskôr vymenil/a spodné prádlo?",
  "Ktorú časť svojho tela považuješ za najviac sexy?",
  "Ako dlho trval tvoj najdlhší sex?",
  "Mal/a si niekedy sex na verejnom mieste? Kde presne?",
  "Máš nejaký fetiš alebo úchylku, ktorú si doteraz tajil/a?",
  'S kým z hráčov by si šiel/šla na "Netflix & chill"?',
  "Na aké porno sa najčastejšie pozeráš?",
  "Ak by si mal/a spraviť striptease – na akú pesničku by to bolo?",
  "Kto z prítomných by ti najlepšie masíroval... nohy?",
  "Opíš svoj najväčší trapas počas sexu... detailne.",
  "Máš skúsenosť s trojkou? Ak nie – s kým by si chcel/a?",
  "Máš niečo, čo ti partner/ka zakázal/a v posteli a teba to lákalo?",
  "Ktoré z tvojich ex by si si ešte raz „dal/a“?",
  "Ktorý herec/herečka ťa vie dostať jedným pohľadom do postele?",
  "Bol/a si niekedy pristihnutý/á pri sexe? Kto vás načapal?",
  "Mal/a si niekedy sen o niekom z prítomných? Ak áno – o kom?",
];

const tasks18Plus = [
  "Ukáž ostatným svoju poslednú fotku v galérii. Ak je nuda – vypi!",
  "Prečítaj nahlas poslednú správu, ktorú si niekomu flirtujúco napísal/a",
  "Simuluj orgazmus pred skupinou... alebo vypi 2 panáky",
  "Daj niekomu masáž ramien... ale so zavretými očami",
  "Nakresli penis... so zavretými očami",
  "Vymysli sexy prezývku pre osobu po tvojej pravici",
  "Napíš do poznámok najšpinavšiu správu, akú by si niekomu poslal – a prečítaj ju nahlas",
  "Olíž hráčovi prst... ktorý si vyberieš ty",
  "Zatancuj „lap dance“ (môže byť aj cez oblečenie) niekomu, koho si zvolíš",
  "Hráč vľavo ti povie, ktorú časť tela máš ukázať – buď ukáž, alebo vypi",
  "Prezraď meno niekoho, koho by si chcel/a vidieť nahého/nahú",
  "Vymysli pikantnú reklamu na lubrikačný gél",
  "Zahráš 10 sekúnd zvukový klip „sexi hlasu“ – ak to ostatní neuznajú, piješ",
  "Pošepkaj niekomu do ucha niečo, čo by si mu povedal/a po treťom pohári vína",
  "Urob selfie, na ktorej vyzeráš najviac „chceš ma“ – a ukáž ju skupine",
];

const duel18Plus = [
  "Kto spraví lepší sexi pohľad do kamery – hlasovaním určí skupina",
  "Zatancujte spolu na imaginárny sexi beat... kto sa skôr zasmeje, prehral",
  "Flirtovacia výzva: kto za 10 sekúnd presvedčí druhého, aby si s ním išiel na drink?",
  "Pretláčanie rukou... kto prehrá, dá tomu druhému bozk na líce",
  "Oči do očí – kto uhne pohľad ako prvý, prehral a pije",
  "Každý povie jednu špinavú vetu – kto znie viac ako z porna, prehráva",
];
