const questions = [
  "Všetci chlapci si vypijú... a dajú kompliment osobe po svojej pravici",
  "Čoho sa bojíš viac než pondelka ráno?",
  "Povedz najlepší (alebo najhlúpejší) vtip, aký poznáš",
  "Čo ťa vytočí tak, že by si najradšej hodil/a ovládač o stenu?",
  "3. osoba naľavo od teba – pohárik a story z detstva!",
  "Všetky ženy si dajú panáka... alebo povedia svoju guilty pleasure",
  "Vypi, alebo označ hráča, ktorý vypije za teba... a povie tvoju najlepšiu vlastnosť",
  "Vyber si osobu, s ktorou by si prežil zombie apokalypsu – a prečo práve ona?",
  "Čo by si na sebe zmenil/a... okrem exa?",
  "S kým z hráčov by si si vedel/a predstaviť prespať na gauči... nahý/á?",
  "Vymysli nový produkt... ktorý by vyriešil problém: opitosť bez hanby",
  "Povedz, prečo by si šiel/šla na rande s hráčom podľa vlastného výberu... aj keby mal/a Crocsy",
  "Ktorý hráč je podľa teba Batman... a kto určite Robin? Zdôvodni!",
  "So ktorou celebritou by si najradšej mal/a horúcu letnú aféru?",
  "Ak ti padlo nepárne číslo – piješ. Ak párne – piješ s osobou po pravici.",
  "Tvoj najbizarnejší zlozvyk, ktorý ťa (ne)robí sexy?",
  "Vyber hráča a povedz, čo ťa na ňom vytáča... s láskou ❤️",
  "Názov tvojej biografie... ktorá sa stane Netflix hitom",
  "Kde budeš o 10 rokov... a koho z prítomných budeš mať stále v živote?",
  "Tvoja najväčšia slabosť... ktorú považuješ za sexy",
];

const challengeTasks = [
  "Vymenuj všetkých 6 šachových figúrok – bez Googlu!",
  "Vyzuj si obidve ponožky a daj si ich na ruky na 2 kolá",
  "Vymenuj 4 mestá v ČR... ktoré nie sú Praha (easy mode off)",
  "Vymenuj 4 hlavné mestá mimo Európy... a pridaj k nim drink, ktorý tam určite pijú",
  "Prines niečo kovové a povedz, prečo je to sexy",
  "Vymenuj 5 mien na P... a povedz, s ktorým by si sa vyspal/a",
  'Postni fotku na story s textom: "Ten večer začína nevinne..."',
  "Prines niečo žlté a povedz, aké by to bolo, keby to bolo živé",
  "Prines niečo drevené a povedz, na čo by sa to dalo použiť v 50 odtieňoch sivej",
  "Zlož 4-veršovú báseň o alkohole a hanbe",
  "Vypi. Ale najprv povedz „na čo“ piješ dnes najviac",
  "Sprav 5 drepov... pri každom povedz jednu nadávku (neopakovateľnú!)",
  "Urob selfie a pošli ju osobe, s ktorou si mal/a najhoršie rande",
];

const duel = [
  "Strihnite si – kto prehrá, vypije 2x",
  "Kto skôr žmurkne – prehrávajúci rozpráva s prízvukom ďalšie 2 kolá",
  "Kto sa skôr zasmeje – prehráva a musí povedať trápnu historku",
  "Palcová hra – kto prehrá, urobí kompliment tomu druhému v rýmoch",
  "Pretláčanie rukou – alebo pohľadom, ak chcete menej fyzicky",
  "Otvor SMS aplikáciu so zavretými očami a prečítaj 1. slovo, ktoré uvidíš – vymysli z neho vtip",
];

const tasks = [
  "Vypi – alebo sa snaž 10 sekúnd flirtovať s fľašou",
  "Vyzleč si 1 vec... bez toho, aby si povedal/a čo to je",
  "Vymieňaj si s hráčom veci, kým sa necítite trápne",
  "Prehovor kanibala, aby ťa nezjedol... ako keby si bol/a nahý/á a smrdíš",
  "Vezmi predmet a drž ho oboma rukami celé 2 kolá – aj ak budeš piť!",
  "Zahraj sa na plačúce dieťa, ktoré nedostalo iPhone",
  "Zahryzni si do jazyka a odrecituj abecedu – a názov porno stránky",
  "Skús si olízať lakeť... a popíš to zmyselne",
  "Vydrž lastovičku aspoň 5 sekúnd – alebo vypi!",
  "Nechaj sa šteklit 7 sekúnd – alebo zaspievaj Despacito",
  "Rozosmej hráča do 10 sekúnd – ak nie, piješ ty",
  "Nakresli trojuholník jednou rukou, kruh druhou – a oboje súčasne nazvi „umenie“",
  "Osoba po ľavici ti dá symbolickú facku... alebo pusu",
  "Vymenuj 5 zvierat, ktoré by v ZOO určite robili bordel",
  "Vymenuj 3 veci, ktoré pokazili tvoje rande... a ktoré by ho vylepšili",
];

const facts = [
  "Tvoja najtrápnejšia story – nech to bolí!",
  "Kedy si sa prvýkrát opil – a kde si sa zobudil/a?",
  "Skúsil/a si marihuanu? Opíš to ako review na Google",
  "Kedy si sa najviac strápnil/a pred crushom?",
  "Vyber hráča a povedz o ňom niečo... čo by možno nechcel vedieť jeho ex",
  "Už si čúral/a v bazéne? Sám/a? Svedkovia?",
  "Koľko ľudí si bozkával/a za posledný rok?",
  "Popíš posledný priestupok... a daj mu hodnotenie zábavnosti (1–10)",
  "Kedy si sa najviac opil/a a čo ťa prebudilo?",
  "Akú najtrápnejšiu vec si si kúpil/a – a ešte ju máš?",
  "Najbizárnejšie miesto, kde si zaspal/a – a prečo si tam bol/a?",
  "Ukradol/a si niečo? A ak áno, bolo to aspoň worth it?",
  "Ako dlho si sa najviac nesprchoval/a... a prečo?",
];
